$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        700:{
            items:3
        },
        1280:{
            items:5
        }
    }
})